spring:
  datasource:
    url: jdbc:mysql://localhost:3306/vote_program?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 0
      timeout: 3000
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 2

server:
  port: 8080

logging:
  file:
    name: vote.log
    path: var/log

jwt:
  secret: jWT6jV9qyT3Qx#pLmZgXn2r5u8x/A?D(G+KbPeShVkYp3s6v9y$B&E)H@McQfTjWn

